### ISSUE TITLE
Not working since HA 2025.1

### ISSUE THREAD

**Issue by dexmorgan8888** [Codestian/ha-lta#16]
Since upgrade to 2025.1, this integration has started warning.

HA self check (before restart) gives warning below:
`Configuration warnings

Platform error 'sensor' from integration 'lta' - cannot import name 'TIME_MINUTES' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)`

Edit: This issue was raised last year as deprecated warning (to be removed 2025.1) and apparently fixed. Is the fix not working or am I missing something?

**Comment by dexmorgan8888** [comment]
Somehow the actual code of my integration (sensor.py) is not updated even though the version is 0.30.

I manually updated it and it worked.
Sorry, my bad. Issue closed.
